const QUESTIONNAIRE = [
  {
    id: "ch1",
    title: "Chapitre 1 — Racines et famille d'origine",
    questions: [
      { id: "ch1-q1", text: "Quel est ton tout premier souvenir d'enfance ?" },
      { id: "ch1-q2", text: "Décris la maison ou l'appartement où tu as grandi. À quoi ça ressemblait, ça sentait quoi, ça sonnait comment ?" },
      { id: "ch1-q3", text: "Quelle est la plus vieille histoire familiale qu'on t'a transmise, un événement d'avant ta naissance ?" },
      { id: "ch1-q4", text: "Parle-moi de tes parents. Comment étaient-ils avec toi ?" },
      { id: "ch1-q5", text: "Parle-moi de tes grands-parents." },
      { id: "ch1-q6", text: "Quels étaient les récits, blagues ou chansons classiques de ta famille ?" },
      { id: "ch1-q7", text: "Qui étaient tes proches ou cousins préférés, et pourquoi ?" },
      { id: "ch1-q8", text: "Quel événement historique ou culturel t'a marqué durant ton enfance ?" },
    ],
  },
  {
    id: "ch2",
    title: "Chapitre 2 — Enfance, l'école et l'identité",
    questions: [
      { id: "ch2-q1", text: "Comment étais-tu enfant ? Qu'auraient dit tes amis d'enfance de toi ?" },
      { id: "ch2-q2", text: "Étais-tu bon élève ? Quelles matières aimais-tu, lesquelles détestais-tu ?" },
      { id: "ch2-q3", text: "Y a-t-il un enseignant qui t'a marqué ? Qu'a-t-il fait pour ça ?" },
      { id: "ch2-q4", text: "Comment était le lycée pour toi socialement, pas seulement scolairement ?" },
      { id: "ch2-q5", text: "As-tu eu un mentor qui a changé ta trajectoire ?" },
      { id: "ch2-q6", text: "Quel était ton rêve d'enfant, ce que tu voulais devenir plus tard ?" },
    ],
  },
  {
    id: "ch3",
    title: "Chapitre 3 — Amour et relations",
    questions: [
      { id: "ch3-q1", text: "Quand es-tu tombé amoureux pour la première fois ?" },
      { id: "ch3-q2", text: "Parle-moi de ta compagne. Comment vous êtes-vous rencontrés ?" },
      { id: "ch3-q3", text: "Raconte votre histoire, vos débuts." },
      { id: "ch3-q4", text: "Qu'est-ce que tu admires le plus chez elle ?" },
      { id: "ch3-q5", text: "Qu'as-tu appris sur toi-même à travers cette relation ?" },
      { id: "ch3-q6", text: "Qu'est-ce que tu voudrais dire à ton fils que tu ne lui as peut-être jamais dit ?" },
      { id: "ch3-q7", text: "Es-tu fier des gens que tu aimes ? Pourquoi ?" },
    ],
  },
  {
    id: "ch4",
    title: "Chapitre 4 — Travail, ambitions et tournants",
    questions: [
      { id: "ch4-q1", text: "Parle-moi de ton premier travail. Qu'en as-tu retenu ?" },
      { id: "ch4-q2", text: "Comment as-tu pris la décision de te lancer dans l'agriculture biologique ?" },
      { id: "ch4-q3", text: "Quel a été le tournant le plus marquant de ta vie professionnelle ?" },
      { id: "ch4-q4", text: "Qu'est-ce que ce métier t'a appris sur toi-même ?" },
      { id: "ch4-q5", text: "Comment as-tu vécu la liquidation de ton entreprise, et qu'en retiens-tu aujourd'hui ?" },
      { id: "ch4-q6", text: "Que recherches-tu maintenant dans ta reconversion ?" },
      { id: "ch4-q7", text: "Quelle place le travail occupe-t-il dans ta vie, comparé au reste ?" },
    ],
  },
  {
    id: "ch5",
    title: "Chapitre 5 — Valeurs, croyances et vision du monde",
    questions: [
      { id: "ch5-q1", text: "Quelles sont les valeurs les plus importantes à tes yeux ?" },
      { id: "ch5-q2", text: "Quelles sont tes croyances, religieuses ou spirituelles, et comment ont-elles évolué ?" },
      { id: "ch5-q3", text: "Qu'est-ce qui te met en colère, et qu'est-ce qui te rend fier ?" },
      { id: "ch5-q4", text: "Comment décrirais-tu ta personnalité à quelqu'un qui ne te connaît pas du tout ?" },
      { id: "ch5-q5", text: "Quel est ton rapport à la vérité et au mensonge, à l'autorité ?" },
      { id: "ch5-q6", text: "Quel sujet ou quelle question philosophique t'obsède ou te passionne particulièrement ?" },
    ],
  },
  {
    id: "ch6",
    title: "Chapitre 6 — Épreuves, regrets et résilience",
    questions: [
      { id: "ch6-q1", text: "As-tu des regrets ? Lesquels ?" },
      { id: "ch6-q2", text: "Y a-t-il une période difficile de ta vie qui t'a transformé ?" },
      { id: "ch6-q3", text: "Comment as-tu traversé les moments les plus durs ?" },
      { id: "ch6-q4", text: "Si tu pouvais revenir en arrière, changerais-tu quelque chose ?" },
      { id: "ch6-q5", text: "Comment ta vie a-t-elle été différente de ce que tu imaginais plus jeune ?" },
      { id: "ch6-q6", text: "Quelles sont les leçons les plus importantes que la vie t'a apprises ?" },
    ],
  },
  {
    id: "ch7",
    title: "Chapitre 7 — Bonheur, humour et légèreté",
    questions: [
      { id: "ch7-q1", text: "Quel a été l'un des moments les plus heureux de ta vie ?" },
      { id: "ch7-q2", text: "Décris ta journée idéale." },
      { id: "ch7-q3", text: "Y a-t-il des histoires drôles ou des souvenirs marrants que tu veux raconter ?" },
      { id: "ch7-q4", text: "Qu'est-ce qui te fait rire, encore aujourd'hui ?" },
      { id: "ch7-q5", text: "Quelles sont tes passions, ce qui t'anime au quotidien ?" },
    ],
  },
  {
    id: "ch8",
    title: "Chapitre 8 — Messages pour les générations futures",
    questions: [
      { id: "ch8-q1", text: "Quelle sagesse voudrais-tu transmettre à ceux qui écouteront cela dans le futur ?" },
      { id: "ch8-q2", text: "Quels sont tes espoirs pour ton fils, pour ses enfants ?" },
      { id: "ch8-q3", text: "Y a-t-il quelque chose que tu n'as jamais dit à quelqu'un et que tu voudrais dire maintenant ?" },
      { id: "ch8-q4", text: "Comment aimerais-tu qu'on se souvienne de toi ?" },
      { id: "ch8-q5", text: "Si c'était notre toute dernière conversation, qu'aurais-tu envie de dire ?" },
      { id: "ch8-q6", text: "Quel conseil donnerais-tu à ton fils, ou même à ses futurs enfants ?" },
    ],
  },
];
